.\"
.\" Copyright (c) 2018 Steven Roberts <sroberts@fenderq.com>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: April 21 2018 $
.Dt YOYO 1
.Os
.Sh NAME
.Nm yoyo
.Nd cryptographically encrypt and decrypt
.Sh SYNOPSIS
.Nm yoyo
.Op Fl d
.Op Fl k Ar keyfile
.Sh DESCRIPTION
The
.Nm
utility will read from stdin and write to stdout.
The stream is encrypted by default unless otherwise specified.
.Pp
The options are as follows:
.Bl -tag -width Dsskeyfile
.It Fl d
Decrypt the stream.
.It Fl k Ar keyfile
Read passphrase from
.Ar keyfile .
.El
.Sh EXAMPLES
Encrypt a file using a passphrase:
.Dl $ yoyo < plaintext.file > ciphertext.file
.Pp
Decrypt a file using a passphrase:
.Dl $ yoyo -d < ciphertext.file > plaintext.file.2
.Sh SEE ALSO
.Xr pledge 2 ,
.Xr bcrypt_pbkdf 3 ,
.Xr EVP_chacha20 3
.Sh AUTHORS
.An Steven Roberts <sroberts@fenderq.com>
